version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: docker/gradle-app/dockerfile
    ports:
      - 8080:8080
    depends_on:
      - dynamodb-local
    volumes:
      - ./:/home/gradle/src
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
      DYNAMO_DB_TABLE_NAME: 'classifications'
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      MICRONAUT_ENVIRONMENTS: 'development'
    links:
      - dynamodb-local
  
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal